# Generated by Django 3.1.4 on 2023-04-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_date_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_view',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=140),
        ),
    ]
